#!/bin/sh

echo "DOTFILES == $DOTFILES"

DOTFILES_VERSION="$(cat $DOTFILES/version)"

main() {
	echo "uninstalling dotfiles $DOTFILES_VERSION"

	echo "-> removing $DOTFILES"
	rm -rf "$DOTFILES"
	echo "-> removing references to dotfiles"
	$DOTFILES/scripts/reset-zshrc
}
main
