#!/bin/sh

DOTFILES=${DOTFILES:-~/dotfiles}
DOTFILES_VERSION="$(cat $DOTFILES/version)"
DOTFILES_LATEST_VERSION="$(curl -fsSL https://raw.githubusercontent.com/schulke-214/dotfiles/master/version)"

# dotfiles-clear-directories() {
#	rm -rf "$DOTFILES/dependencies"
#	rm -rf "$DOTFILES/tmp"
# }

# update functions

main() {
	echo "updating dotfiles $DOTFILES_VERSION -> $DOTFILES_LATEST_VERSION"

    if [ $DOTFILES_VERSION == $DOTFILES_LATEST_VERSION ]; then
        echo "-> already up to date"
        return 0
    fi

	echo
	echo "-> clearing dependencies and temp files"
	# dotfiles-clear-directories
	echo "-> downloading dotfiles $DOTFILES_LATEST_VERSION"

    local UPDATING_FAILED="updating failed.. consider reinstalling, or open an issue on github!"

    cd $DOTFILES
    git stash &>/dev/null || {
        echo $UPDATING_FAILED
        exit 1
    }

    git pull --force &>/dev/null || {
        echo $UPDATING_FAILED
        exit 1
    }

    git stash pop &>/dev/null || {
        echo $UPDATING_FAILED
        exit 1
    }

    cd - &>/dev/null
	echo "-> installing dependencies"

    echo

    echo "dotfiles $DOTFILES_LATEST_VERSION are now installed."
}

main

#### use arg to specify only deps

# dotfiles-update-deps-only() {
# 	echo "updating dotfile dependencies"
# 	echo

# 	echo "-> clearing dependencies and temp files"
# 	dotfiles-clear-directories
# 	echo "-> installing dependencies"
# }
