inherits = "base16_default_dark"

"ui.background" = {}
"ui.virtual.ruler" = { fg = "base02", bg = "base01" }
"ui.cursorline.primary" = { fg = "base02", bg = "base01" }
"ui.cursorline.secondary" = { fg = "base02", bg = "base01" }
"ui.cursorcolumn.primary" = { fg = "base02", bg = "base01" }
"ui.cursorcolumn.secondary" = { fg = "base02", bg = "base01" }
"comment" = "base02"

[palette]
base00 = "#0f080e" # Default Background
base01 = "#1d161c" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#4d464c" # Selection Background
base03 = "#5d565c" # Comments, Invisibles, Line Highlighting
base04 = "#bfaba7" # Dark Foreground (Used for status bars)
base05 = "#cfbbb7" # Default Foreground, Caret, Delimiters, Operators
base06 = "#dfcbc7" # Light Foreground (Not often used)
base07 = "#ffebe7" # Light Background (Not often used)
base08 = "#f6b0ad" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#ffc8ae" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#ffdbae" # Classes, Markup Bold, Search Text Background
base0B = "#c3c190" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#d3d1a0" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#cfd3fe" # Functions, Methods, Attribute IDs, Headings
base0E = "#edc3e0" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#fde3f0" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
