export GOPATH=$(go env GOPATH)
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$DOTFILES/bin:$PATH"
export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"

export GPG_TTY=$(tty)
export ZSH="$DOTFILES/dependencies/oh-my-zsh"

# load plugin configuration
source $DOTFILES/config/zsh/plugins

# load dependencies
source $DOTFILES/dependencies/oh-my-zsh/oh-my-zsh.sh
source $DOTFILES/dependencies/zsh-nvm/zsh-nvm.plugin.zsh

# load configuration
source $DOTFILES/config/zsh/prompt
source $DOTFILES/config/zsh/aliases