#!/usr/bin/env node

const fs = require('fs');
const os = require('os');

const zshrc = `${os.homedir()}/.zshrc`;

fs.readFile(zshrc, 'utf8', (e, file) => {
	if (e) throw e;

	const targetLine = `source "${process.env['DOTFILES']}/zshrc"`;
	const filtered = file.split('\n').filter(line => line !== targetLine);

	fs.writeFile(zshrc, filtered.join('\n'), e => {
		if (e) throw e;
	});
});
