#!/usr/bin/env python3
import subprocess
import argparse


parser = argparse.ArgumentParser()
parser.add_argument("target", type=str, help="target ip")
parser.add_argument("-w", "--workers", type=int, default=10,  help="Number of workers")
parser.add_argument("-l", "--lifetime", type=int, default=60, help="Lifetime of the workers")
args = parser.parse_args()

workers = args.workers
lifetime = args.lifetime
target = args.target

processes = []

for i in range(0, workers):
    proc = subprocess.Popen(['ping', target])
    processes.append(proc)

for proc in processes:
    print(proc.pid)
    proc.terminate()
    status = proc.returncode

    if status:
        print(proc.id, "failed")
    else:
        print(proc.id, "terminated")

print(processes)
print(workers, lifetime, target)    
